name: Basil Data Logger

on:
  schedule:
    # Runs every 3 hours
    - cron: '0 * * * *'
  workflow_dispatch: # allows manual triggering from GitHub Actions UI

jobs:
  log-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gspread oauth2client
          pip install firebase-admin requests
          
      #- name: Run basil logger
      #  env:
      #    GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      #  run: |
      #    echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json
      #    python log_basil_data.py
      # printf '%s' "${{ secrets.FIREBASE_KEY_JSON }}" > firebase-key.json
      - name: Decode and write Firebase key
        run: |
          echo "${{ secrets.FIREBASE_KEY_BASE64 }}" | base64 -d > firebase-key.json
      - name: Run basil logger
        run: python log_basil_data.py
